version: '3'
services:
  ptl-media:
    build: media
    expose:
      - "8888/tcp"
      - "0-65535/udp"
    ports:
      - "0-65535/udp"
  ptl-db:
    image: redis
    expose:
    - "6379"
  ptl-signal:
    build: signal
    ports:
    - "5051:80"
    depends_on:
    - ptl-media
    - ptl-db
