version: '3'
services:
  ptl-media:
    build: media
    network_mode: host
  ptl-db:
    image: redis
    expose:
    - "6379"
  ptl-signal:
    build: signal
    ports:
    - "5051:80"
    depends_on:
    - ptl-media
    - ptl-db
